### ISSUE TITLE
Added opus

### ISSUE THREAD

**Issue by irthomasthomas** [sblakey/llm-bedrock-anthropic#13]
Hi, 

claude 3 opus is now available on us-west-2.

I added a PR. In the meantime, you can install it like so:
```bash
git clone --depth 1 --branch claude-3-opus https://github.com/ShellLM/llm-bedrock-anthropic.git     
cd llm-bedrock-anthropic
llm install .
```

**Comment by sblakey** [comment]
Merged it in. I've also added an option to specify the bedrock model_id on the command line, which should allow people to work with newer models without waiting for a code push and PyPi update (as well as work with provisioned capacity, custom models, etc.)

**Comment by sblakey** [comment]
Pushed with release 0.4.3
